name: BookManager
version: 0.2
main: com.LRFLEW.bukkit.book.Plugin
author: LRFLEW
description: Allows players to edit their Written Books

commands:
  unsign:
    description: Unsigns Written Books
    aliases: us
    permission: bookmanager.unsign
    usage: "Hold a Written Book and use: /<command>"
    permission-message: You don't have permission to unsign books
  rnbook:
    description: Renames Written Books
    aliases: rb
    permission: bookmanager.rnbook
    usage: "Hold a Written Book and use: /<command> <name>"
    permission-message: You don't have permission to rename books
  rnauth:
    description: Changes the Author Name for Written Books
    aliases: ra
    permission: bookmanager.rnauth
    usage: "Hold a Written Book and use: /<command> <name>"
    permission-message: You don't have permission to change the author name of books
  copybook:
    description: Copies Written Books
    aliases: cb
    permission: bookmanager.copy
    usage: "Hold a Written Book and use: /<command> [amount]"
    permission-message: You don't have permission to copy books
  savetxt:
    description: Saves Written Books as .txt files in the plugin folder
    aliases: st
    permission: bookmanager.savetxt
    usage: "Hold a Written Book and use: /<command>"
    permission-message: You don't have permission to use that command

permissions:
  bookmanager.unsign:
    description: allows player to use /unsign on their own books
    default: true
  bookmanager.unsign.other:
    description: allows player to use /unsign on other player's books
    default: op
    children:
      bookmanager.unsign: true
  bookmanager.rnbook:
    description: allows player to use /rnbook on their own books
    default: true
  bookmanager.rnbook.other:
    description: allows player to use /rnbook on other player's books
    default: op
    children:
      bookmanager.rnbook: true
  bookmanager.rnauth:
    description: allows player to use /rnauth
    default: op
  bookmanager.copy:
    description: allows player to use /copybook
    default: true
  bookmanager.copy.free:
    description: allows player to use /copybook without extra materials
    default: op
    children:
      bookmanager.copy: true
  bookmanager.savetxt:
    description: allows player to use /savetxt
    default: op
    
  bookmanager.none:
    description: removes all permissions from player for BookManager
    children:
      bookmanager.unsign: false
      bookmanager.unsign.other: false
      bookmanager.rnbook: false
      bookmanager.rnbook.other: false
      bookmanager.rnauth: false
      bookmanager.copy: false
      bookmanager.copy.free: false
      bookmanager.savetxt: false
  bookmanager.default:
    description: gives player control over their own books only
    children:
      bookmanager.unsign: true
      bookmanager.unsign.other: false
      bookmanager.rnbook: true
      bookmanager.rnbook.other: false
      bookmanager.rnauth: false
      bookmanager.copy: true
      bookmanager.copy.free: false
      bookmanager.savetxt: false
  bookmanager.admin:
    description: gives player control over any book
    children:
      bookmanager.unsign.other: true
      bookmanager.rnbook.other: true
      bookmanager.rnauth: true
      bookmanager.copy.free: true
      bookmanager.savetxt: true